### ISSUE TITLE
partkart.com/ and Makercam.com have gone down

### ISSUE THREAD

**Issue by BarbourSmith** [Jack000/PartKAM#1]
It seems that MakerCAM and http://partkart.com/ have gone down today. My own hosted copy at https://www.maslowcnc.com/makercam is also not working any longer. 

I know you haven't touched this project in a few years @Jack000, but do you have any idea what is going on and how we could fix it? Over in the Maslow CNC forums we depend on it 😀 

https://forums.maslowcnc.com/t/makercam-is-down/5293

**Comment by Jack000** [comment]
ah, didn't know anyone was using that domain. I'm not sure why maslow's version would be affected, as it just loads the swf locally.

I'll put it on a new domain, but in the meantime you could just download the swf and run it on your desktop: http://maslowcnc.com/s/partkam.swf

**Comment by Jack000** [comment]
re-hosted at https://partkam.com/

**Comment by BarbourSmith** [comment]
Thank you!! We absolutely love it and it's the backbone of our community 😁 👍 👍 ❤️

**Comment by cmighells** [comment]
Like so many people I was reliant on Makercam for converting svg to gcode.  Then it went down.  Then Partkam came up and then down.  I am still using Makercam but I do it offline.   Go to Makercam.com and right click to download the website.  Then download Adobe Flash Player and load the file.  Presto!  You have Makercam working again.  This is April 9, 2021 and the website is still up so, if you hurry, you can set it up for offline use.  Enjoy!
